version: "3"

services:
  memcached:
    build:
      context: .
      dockerfile: ./docker/store/Dockerfile
    ports:
       - 11211:11211
  cli:
    build:
      context: .
      dockerfile: ./docker/cli/Dockerfile
    volumes:
      - .:/reddit_cli_app
    ports:
      - 8000:8000
